name: Java CI

on:
  push:
    branches:
      - main  # Change this to your main branch
  schedule:
    - cron: '0 0 * * 1'  # This cron expression runs at 00:00 on Monday (day-of-week 1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          java -version  # Verify Java installation

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests


      - name: Build with Maven
        run: mvn clean install -B

      - name: Set up Env Variable
        run: |
          echo "AUTH_TOKEN=${{ secrets.AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Run Java application
        run: java -jar target/smartsheet-automation-0.0.1-SNAPSHOT.jar
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN}}

